version: 2.1

workflows:
  version: 2

  main:
    jobs:
      - lintSyntax
      - lintStaticAnalysis
      - test80
      - test81
      - test82
      - test83
jobs:
  lintStaticAnalysis:
    docker:
      - image: cimg/php:8.1
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: sudo composer self-update && composer install -n --prefer-dist
      - run:
          name: Static analysis
          command: composer run lint-static-analysis

  lintSyntax:
    docker:
      - image: cimg/php:8.1
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: sudo composer self-update && composer install -n --prefer-dist
      - run:
          name: Install php-cs-fixer
          command: mkdir -p tools/php-cs-fixer && composer require --dev --working-dir=tools/php-cs-fixer friendsofphp/php-cs-fixer
      - run:
          name: Run syntax test
          command: tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --dry-run --stop-on-violation -v

  test80:
    docker:
      - image: cimg/php:8.0
    steps:
      - checkout
      - run: { name: "Install dependencies", command: "sudo composer self-update && composer install -n --prefer-dist" }
      - run: { name: "Test suite", command: "composer test-quick-fail" }

  test81:
    docker:
      - image: cimg/php:8.1
    steps:
      - checkout
      - run: { name: "Install dependencies", command: "sudo composer self-update && composer install -n --prefer-dist" }
      - run: { name: "Test suite", command: "composer test-quick-fail" }

  test82:
    docker:
      - image: cimg/php:8.2
    steps:
      - checkout
      - run: { name: "Install dependencies", command: "sudo composer self-update && composer install -n --prefer-dist" }
      - run: { name: "Test suite", command: "composer test-quick-fail" }

  test83:
    docker:
      - image: cimg/php:8.3
    steps:
      - checkout
      - run: { name: "Install dependencies", command: "sudo composer self-update && composer install -n --prefer-dist" }
      - run: { name: "Test suite", command: "composer test-quick-fail" }

